version: '1.0'

services:
  api:
    build: 
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL
      - API_PORT
    ports:
      - 3000:3000
    command: npm run dev